name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H 54.227.112.147 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          remote_host: "54.227.112.147"
          remote_user: "ubuntu"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          args: "-rltgoDzvO --delete --exclude 'public/index.php' --exclude 'Database/MySQLWrapper.php'"
          source: "./"
          target: "/home/ubuntu/web"
